//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBook
    {
        public int BooksId { get; set; }
        public Nullable<int> AccNo { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Author { get; set; }
        public string Edition { get; set; }
        public string Publication { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string Subject { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Remarks { get; set; }
    }
}
