//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasterAcademicDetail
    {
        public int MasterAcademicDetailsId { get; set; }
        public Nullable<int> PersonalInfoId { get; set; }
        public Nullable<int> BatchNo { get; set; }
        public Nullable<int> RollNo { get; set; }
        public string TuRegistrationNo { get; set; }
        public string PreviousDegree { get; set; }
        public string AdmissionDate { get; set; }
        public string Duration { get; set; }
        public string PassYear { get; set; }
        public string ProjectTitle { get; set; }
        public string ThesisTitle { get; set; }
        public string VivaDate { get; set; }
        public Nullable<bool> IsPassed { get; set; }
        public string Remarks { get; set; }
    }
}
